# Generated by Django 6.0.7 on 2026-07-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePeludo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('es_estrella', models.BooleanField(default=False, help_text='Mostrar en portada')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cliente Peludo',
                'verbose_name_plural': 'Clientes Peludos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(choices=[('✂️', 'Tijeras'), ('🛁', 'Bañera'), ('💅', 'Manicura'), ('💆', 'Spa'), ('🎀', 'Accesorios'), ('🐾', 'Pata')], default='🐾', max_length=10)),
                ('precio_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CitaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dueno', models.CharField(max_length=100, verbose_name='Nombre del dueño')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('nombre_mascota', models.CharField(max_length=100, verbose_name='Nombre de la mascota')),
                ('raza_mascota', models.CharField(blank=True, max_length=100, verbose_name='Raza (opcional)')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora deseada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peluqueria.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Reserva de Cita',
                'verbose_name_plural': 'Reservas de Citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
